version: '3.8'

services:

  postgres:
    container_name: postgres
    image: postgres:16
    networks:
      - pong_website
    restart: always
    env_file: backend/.env
    expose:
      - 5432
    volumes:
      # FOR WINDOWS DOCKER DESKTOP:
      # First create a volume: docker volume create --name=postgres-data
      - postgres-data:/var/lib/postgresql/data
      - ./postgres/create_round.sql:/docker-entrypoint-initdb.d/create_round.sql

  redis:
    container_name: redis
    image: redis:6.2.6
    networks:
      - pong_website
    restart: always
    environment:
      - TZ=Europe/Paris
    volumes:
      - ./redis/data:/data
    ports:
      - 6379:6379

  backend:
    container_name: backend
    init: true
    build: ./backend
    volumes:
      - ./backend:/usr/src/app
      - ./media_volume:/usr/src/app/media
    networks:
      - pong_website
    depends_on:
      - postgres
      - redis
    env_file: backend/.env

  nginx:
    container_name: nginx
    build: ./nginx
    volumes:
      - ./nginx/html:/usr/share/nginx/html
      - ./media_volume:/usr/share/nginx/media
    ports:
      - 443:443
      - 80:80
    networks:
      - pong_website
    depends_on:
      - backend


networks:
  pong_website:
    driver: bridge

# FOR WINDOWS DOCKER DESKTOP:
volumes:
  static_volume:
  postgres-data:
    external: true
