-- Creation of round table
CREATE TABLE IF NOT EXISTS lobby_round (
  id INT GENERATED BY DEFAULT AS IDENTITY, 
  name varchar (15) UNIQUE NOT NULL,
  short_name varchar(4) UNIQUE NOT NULL,
  level integer UNIQUE NOT NULL,
  player integer UNIQUE NOT NULL,
  PRIMARY KEY (id)
);

INSERT INTO lobby_round
	(name, short_name, level, player)
	VALUES
	('FINAL', 'F', 1, 2),
	('SEMIFINALS', 'SF', 2, 4),
	('QUARTERFINALS', '1/4', 3, 8),
	('ROUND OF 16', '1/8', 4, 16)
	;